### ISSUE TITLE
cannot stop a background process after 'gork'ing it

### ISSUE THREAD

**Issue by manojnakp** [bingxueshuang/gork#1]
I just spawned web server using gork:

```bash
$ gork npm run dev
```
Now I cannot stop the dev server, unless I remember the exact command or know the pid.

```bash
$ ps -C "npm"
  PID TTY    TIME     CMD
14627 pts/0  00:00:00 npm
14691 pts/0  00:00:00 npm
$ kill 14627
```

Can any better way be provided via gork?

**Comment by bingxueshuang** [comment]
The pid of the process can be returned as soon as it is launched. Thus, just calling kill later would do the job
